import { alpha } from "@mui/material";

/** Shared dark-workspace chrome — flat, thin borders, no theme CTA gradient bleed. */
export const judgeUi = {
  panelRadius: 0.75,
  hairline: alpha("#fff", 0.06),
  hairlineStrong: alpha("#fff", 0.1),
  select: {
    minWidth: 118,
    height: 28,
    fontSize: 12,
    fontWeight: 600,
    borderRadius: 0.5,
    color: "#e6edf3",
    bgcolor: alpha("#161b22", 0.95),
    "& .MuiOutlinedInput-notchedOutline": { borderColor: alpha("#fff", 0.2) },
    "&:hover .MuiOutlinedInput-notchedOutline": { borderColor: alpha("#fff", 0.32) },
    "&.Mui-focused .MuiOutlinedInput-notchedOutline": {
      borderColor: "#388bfd",
      borderWidth: "1px",
    },
    "& .MuiSelect-select": { py: 0.45, px: 1.1, display: "flex", alignItems: "center" },
    "& .MuiSvgIcon-root": { color: alpha("#fff", 0.55), right: 4 },
  },
  runBtn: {
    textTransform: "none",
    fontWeight: 600,
    fontSize: 12,
    minHeight: 28,
    px: 1.25,
    borderRadius: 0.5,
    color: alpha("#fff", 0.9),
    borderColor: alpha("#fff", 0.22),
    bgcolor: "transparent",
    "&:hover": { borderColor: alpha("#fff", 0.35), bgcolor: alpha("#fff", 0.04) },
  },
  submitBtn: {
    textTransform: "none",
    fontWeight: 700,
    fontSize: 12,
    minHeight: 28,
    px: 1.5,
    borderRadius: 0.5,
    bgcolor: "#238636",
    color: "#ffffff !important",
    background: "#238636 !important",
    backgroundImage: "none !important",
    boxShadow: "none !important",
    border: `1px solid ${alpha("#3fb950", 0.45)}`,
    letterSpacing: 0,
    "&:hover": {
      bgcolor: "#2ea043",
      background: "#2ea043 !important",
      backgroundImage: "none !important",
      boxShadow: "none !important",
    },
    "&.Mui-disabled": {
      bgcolor: alpha("#238636", 0.35),
      background: `${alpha("#238636", 0.35)} !important`,
      color: `${alpha("#fff", 0.4)} !important`,
      borderColor: alpha("#fff", 0.08),
    },
  },
  menuPaper: {
    bgcolor: "#161b22",
    border: `1px solid ${alpha("#fff", 0.12)}`,
    borderRadius: 0.5,
    mt: 0.5,
    "& .MuiMenuItem-root": {
      fontSize: 12,
      fontWeight: 600,
      color: "#e6edf3",
      minHeight: 32,
      "&:hover": { bgcolor: alpha("#388bfd", 0.12) },
      "&.Mui-selected": { bgcolor: alpha("#388bfd", 0.18) },
    },
  },
} as const;
